version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: hris_nginx
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/api
      - ./build/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - php
  php:
    build:
      context: ./build/php-with-composer
    container_name: hris_php
    expose:
      - "9000"
    volumes:
      - ./api:/var/www/api
    working_dir: /var/www/api
    links:
      - db

  db:
    image: mysql:latest
    container_name: hris_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
    volumes:
      - data-mysql:/var/lib/mysql

volumes:
  data-mysql: {}
